### ISSUE TITLE
'git branch' list items have directory names cut off when using "/"

### ISSUE THREAD

**Issue by pacificpelican** [railsware/upterm#1021]
Sort of an edge case maybe, but at my work we have adopted the (anti-)pattern of using directory names in Git branches, so for example if I am working on bugfixes I might call my branch <code>Dan/bugfixesMay2017</code> or whatever.  Unfortunately when I type <code>git branch</code> in Black Screen it only shows the last part of the name [<code>bugfixesMay2017</code>]

**Comment by mkenne11** [comment]
I was able to replicate this bug. A branch I created was named ```feature/test1```. See screenshot below after running  ```git branches``` in bash terminal showing this branch.
![image](https://cloud.githubusercontent.com/assets/12181805/26449265/9f4b6dfc-4194-11e7-83d5-76187a45fafb.png)

When running the ```git branch``` command in black-screen it shows the ```feature/test1``` branch name truncated to ```test1```. See following screenshot.
![image](https://cloud.githubusercontent.com/assets/12181805/26449366/1f83c7f8-4195-11e7-8a2e-8f081b0e0b6c.png)

**Comment by mkenne11** [comment]
This bug is caused by the ```Branch``` class constructor truncating the branch-name using "/". The "/" character is a valid character in branch names - so it's not always the case that a "/" separates a ref-remotes, ref-tags or ref-heads name from a branch name.

**Comment by mkenne11** [comment]
See suggested fix in PR #1041. The change generates the full branch names including ref-heads, ref-remotes and ref-tags prefixes; and using a regex filter removes these prefixes.

See black-screen screenshot with branch suggestions showing ```feature/test1``` correctly.
![image](https://cloud.githubusercontent.com/assets/12181805/26450112/203814de-4199-11e7-831e-9d83242f10f9.png)
