### ISSUE TITLE
Copying doesn't work

### ISSUE THREAD

**Issue by Leva7** [railsware/upterm#1035]
Whenever I select some text to copy (both the command and the output) and hit Ctrl, the selection disappears, therefore it's not possible to copy text from terminal.  
There's also no right-click-dropdown menu to copy text without the keyboard, that would also be nice.

**EDIT**: the Copy button from the top menu works, however  
Seen on Ubuntu 16.04 64-bit

**Comment by vshatskyi** [comment]
Should work in the latest master. Please reopen otherwise.
