### ISSUE TITLE
Wrapped text of the command output gets overlapped

### ISSUE THREAD

**Issue by Leva7** [railsware/upterm#1036]
Sometimes long outputs of commands get cut out by the next prompt.
Here's a screenshot to demonstrate the problem:
![full](https://cloud.githubusercontent.com/assets/15035286/26281849/dbaa4b54-3e1c-11e7-858a-d98c0254c316.png)

Also the same problem occurs when resizing the window after the output was printed
![resized](https://cloud.githubusercontent.com/assets/15035286/26281856/f5fc29e6-3e1c-11e7-9f8f-db621b8e0bec.png)

Seen on Ubuntu 16.04 64-bit

**Comment by joeldrapper** [comment]
I’ve had the same issue when viewing output from a heroku console.

**Comment by Leva7** [comment]
This issue is still there, in the latest master

**Comment by vlad-shatskyi** [comment]
@Leva7, please try again.
