### ISSUE TITLE
Alt-3 (#) on Mac exits insert mode on terminal editors

### ISSUE THREAD

**Issue by shnupta** [railsware/upterm#1039]
When using a terminal editor like vim in insert mode - if I want to insert a `#` it just exits the insert mode doing the same action as an ESC.

To replicate:
Open vim
Go into insert mode
Try entering # with Alt-3

**Comment by vshatskyi** [comment]
This is expected behavior: we chose to have Alt in Esc+ mode. I've added a comment to the source code with an explanation. https://github.com/railsware/upterm/commit/55da2ac6c641790e0b1fcfe9bd326d9dd8d31343

Also, a related past issue: https://github.com/railsware/upterm/issues/821
