### ISSUE TITLE
Byobu with SSH is ugly

### ISSUE THREAD

**Issue by Dima4ka** [railsware/upterm#1040]
### Steps to reproduce:

* Have a server with byobu installed
* SSH to that server

### Expected:

Nice UI like in standard terminal

### Actual:

See screenshot.
![screen shot 2017-05-22 at 13 03 29](https://cloud.githubusercontent.com/assets/5620695/26320073/7ef8e7f2-3eef-11e7-94ec-2c312a62da94.png)
<img width="1680" alt="screen shot 2017-05-22 at 13 07 15" src="https://cloud.githubusercontent.com/assets/5620695/26320098/9dde64bc-3eef-11e7-981a-289f634da5a0.png">

**Comment by vshatskyi** [comment]
@Dima4ka, could you please share your config? I can't reproduce the repeated status bars issue. Here's how it looks like on my computer:

![image](https://cloud.githubusercontent.com/assets/188928/26494398/2c6ccc8e-4227-11e7-8a1a-3bfe3ef0c4fe.png)
