### ISSUE TITLE
The CWD doesn't update instantly

### ISSUE THREAD

**Issue by Leva7** [railsware/upterm#1051]
When you try to switch to a different folder with `cd`, the statusbar below only updates after the second command
So from this point
![image](https://cloud.githubusercontent.com/assets/15035286/26494208/1c09436c-4237-11e7-991d-8fffcc171f2f.png)
we move to `/home`, but the indicator still says we're in `/`
![image](https://cloud.githubusercontent.com/assets/15035286/26494303/797d4552-4237-11e7-8406-8c4f5ca4c1fc.png)
and then any command execution updates it
![image](https://cloud.githubusercontent.com/assets/15035286/26494388/e50857bc-4237-11e7-81f7-4fbcd9fa23bd.png)

**Comment by vshatskyi** [comment]
This should be fixed in https://github.com/railsware/upterm/releases/tag/v0.2.150 . I can see you use Linux, could you please try to check in the latest master?

**Comment by Leva7** [comment]
Yep, that got it working
