### ISSUE TITLE
History Substitution (!! and other commands) Doesn't Work

### ISSUE THREAD

**Issue by Leva7** [railsware/upterm#1052]
The screenshot in the README claims that when you type `!`, it will show an autocomplete. But for some reason not only does this not show up, the `!!` alias also simply doesn't work.
![image](https://cloud.githubusercontent.com/assets/15035286/26494540/93479f04-4238-11e7-9aae-03cd8a7ffd7a.png)
Seen on Ubuntu 16.04 64-bit

**Comment by vshatskyi** [comment]
Thanks for reporting bugs, @Leva7! It used to work but then somehow broke along the way. I'll try to fix this soon.

**Comment by vshatskyi** [comment]
It seems like I removed history expansion at some point. So we'll need to add support for it from scratch.

**Comment by vshatskyi** [comment]
Closing in favor of https://github.com/railsware/upterm/issues/1009
