### ISSUE TITLE
Search in .bash_history

### ISSUE THREAD

**Issue by Leva7** [railsware/upterm#1058]
It would be nice to have some way of searching through the `.bash_history` file, because sometimes autocomplete doesn't show it in history (if it starts the same as a lot of other commands, `sudo`, for example). Or a way to configure how many history autocompletions are shown

**Comment by vshatskyi** [comment]
For your information, I'm currently working mainly on bugs, so any feature is unlikely to be implemented soon.

**Comment by vlad-shatskyi** [comment]
Please check if the current version of completion works as you expected, @Leva7.
