### ISSUE TITLE
Git status bar only works in repository root

### ISSUE THREAD

**Issue by sombrelain** [railsware/upterm#1066]
The git repository information (branch, changes, etc.) shown in the status bar are only visible when you are in the root directory of the repository. Not sure if this is intended, but I would expect them to also show up in subdirectories of a repository.

One possible fix would be to adjust the `isGitRepository` in the git util to also recursively check parent directories for existing `.git` folders (up to root). I made the change locally and it seems to work fine, unfortunately can't test it on windows right now. 

If no one objects, I'd just make a pull request out of it?

**Comment by vlad-shatskyi** [comment]
Yeah, you can go ahead and open a PR.

**Comment by vlad-shatskyi** [comment]
Fixed.
