### ISSUE TITLE
Upterm error using !! to reissue commands as su

### ISSUE THREAD

**Issue by mikesprague** [railsware/upterm#1068]
Running `sudo !!` to reissue a command with su privileges fails and returns `sudo: !!: command not found`. 

This happens regardless of the previous command. It always fails.

I am using Upterm on Ubuntu 16.04 and receive this error using both Bash and ZSH as my shell. If there's any additional informtaion I can provide that will be helpful, please let me know.

**Comment by vlad-shatskyi** [comment]
A duplicate of https://github.com/railsware/upterm/issues/1009
