### ISSUE TITLE
Text gets randomly split onto multiple lines

### ISSUE THREAD

**Issue by Leva7** [railsware/upterm#1070]
Related to #1036 
For no apparent reason, there are line breaks in long enough output.
This started appearing after the text wrapping had been fixed.
![image](https://cloud.githubusercontent.com/assets/15035286/26722277/a27de18e-47a8-11e7-897c-d59d90b76ee9.png)

Seen on Ubuntu 16.04

**Comment by vlad-shatskyi** [comment]
@Leva7 I hope this time it's fixed properly. Could you please verify in the latest master?
