### ISSUE TITLE
Reduce app size

### ISSUE THREAD

**Issue by Leva7** [railsware/upterm#1071]
Some kind of modularity or simply app size reduction would be nice. As of now, the Linux version, after being packed, weighs 500 MB

**Comment by vlad-shatskyi** [comment]
@Leva7 the  AppImage size is 53MB on my computer. Are you sure its 500 on yours?

**Comment by Leva7** [comment]
@vlad-shatskyi No, I meant that the whole folder weighs 500 MB. Mostly `node_modules` and `dist/linux_unpacked`. Is AppImage the only thing I need to keep for the app to work?

**Comment by vlad-shatskyi** [comment]
Yes, AppImage includes everything needed to run the application.

**Comment by vlad-shatskyi** [comment]
Closing as "won't implement" because 50MB is a reasonable size of an Electron app.
