### ISSUE TITLE
How to know the shortcut keys？

### ISSUE THREAD

**Issue by czs0x55aa** [railsware/upterm#1074]
I want to know the shortcuts it supports.
Thanks.

**Comment by vlad-shatskyi** [comment]
Unfortunately, there is no shortcuts documentation at the moment. Some of them are available in the menu, but the only way to see the complete list is to read this file: https://github.com/railsware/upterm/blob/master/src/views/keyevents/Keybindings.ts

There are two structures: `KeybindingsForActions` and `KeybindingsForMenu`.
