### ISSUE TITLE
Git branch in status bar isn't always updated

### ISSUE THREAD

**Issue by vlad-shatskyi** [railsware/upterm#1076]

**Comment by davidtcdeveloper** [comment]
Not sure if I am experiencing the same situation here. Let me know if you need to move this description to somewhere else.
I have been using upterm for a while and never had any problem with git integration. In version 0.3.0 I noticed that the git branch was not updated in status bar, as described in image below. After subsequent checkouts, the branch indicator was not updated.

![screenshot from 2017-08-08 09-39-33](https://user-images.githubusercontent.com/3853471/29072934-21a3e336-7c20-11e7-87f3-b53a1e5f9dec.png)

This situation happened after a long sequence of `pull`s, `push`es and lots of others operations. 
I could not find a sequence of operations that can lead to this lack of update, but I would be happy to provide more data if you need.

My setup:
upterm 0.3.0.
Ubuntu 17.04.
git repository operated inside upterm only (no external operations affecting git).

**Comment by vlad-shatskyi** [comment]
@davidtcdeveloper next time this happens please open developer tools (`View` -> `Toggle Developer Tools`) and check if there are any errors in the JS console.

**Comment by davidtcdeveloper** [comment]
Great, I will do that.

**Comment by davidtcdeveloper** [comment]
I run into this situation again, this is the log in Console:
```
/tmp/.mount_cChm3q/usr/bin/resources/app.asar/node_modules/rxjs/util/subscribeToResult.js:42 Uncaught Error: Command failed: git "symbolic-ref" "--short" "-q" "HEAD"


    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```
The problem happened after suspending and restoring the computer some times. Do you think it can be related?

**Comment by davidtcdeveloper** [comment]
Same situation, different console output:

```
