### ISSUE TITLE
Silent Renaming? Black Screen -> UpTerm

### ISSUE THREAD

**Issue by muescha** [railsware/upterm#1080]
i just accidental found out that the app is renamed because i tapped in the `Black Screen` app on `Help / Github Repository` and it come up with `upterm`

but there was no hint in the readme about this renaming

there should be:
- a note somewhere in the readme about the renaming (and maybe also why it was renamed)
- i would like to be notified somehow :(

**Comment by vlad-shatskyi** [comment]
Hey, @muescha. Sorry about that, it's just that we had no place to announce this. I thought having the old repository redirecting to the new one would be enough. Hopefully soon we'll have a web-site and a blog.

I'll close this issue as we won't have any more renamings. :)
