### ISSUE TITLE
Ranger isn't rendered correctly

### ISSUE THREAD

**Issue by vlad-shatskyi** [railsware/upterm#1082]

**Comment by vlad-shatskyi** [comment]
@RobertoUa strangely it renders correctly for me. Do you have some custom config?
![image](https://user-images.githubusercontent.com/188928/26863595-3a5f871c-4b5c-11e7-96e9-e72da7ee4863.png)

**Comment by RobertoUa** [comment]
I have borders turned on.
in `~/.config/ranger/rc.conf` set `set draw_borders true`.
