### ISSUE TITLE
Most of the Command does not work - env, docker etc..

### ISSUE THREAD

**Issue by yks0000** [railsware/upterm#1090]
Getting below if we check for env command.

env
Upterm: command "env" not found.

docker ps
Upterm: command "docker" not found.

Please suggest

**Comment by vlad-shatskyi** [comment]
It seems like your `$PATH` is incorrect. what's the output of `echo $PATH`?

**Comment by vlad-shatskyi** [comment]
I was able to reproduce it. It seems that sometimes after executing `cd` `PATH` get broken.

**Comment by vlad-shatskyi** [comment]
It should work now.
