### ISSUE TITLE
Build failing on Linux (Xubuntu 16.04)

### ISSUE THREAD

**Issue by benjamin-rood** [railsware/upterm#1095]
Output of `npm install`:
```
npm WARN enzyme@2.8.2 requires a peer of react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x but none was installed.
npm WARN react-dom@15.5.4 requires a peer of react@^15.5.4 but none was installed.
```

Then, output from `npm run pack`:
```
❯ npm run pack      

> upterm@0.2.158 pack /home/br/Downloads/upterm
> npm run compile && build

npm WARN invalid config loglevel="notice"

> upterm@0.2.158 compile /home/br/Downloads/upterm
> npm run cleanup && npm run tsc && npm run copy-html


> upterm@0.2.158 cleanup /home/br/Downloads/upterm
> rimraf compiled/src


> upterm@0.2.158 tsc /home/br/Downloads/upterm
> tsc

src/Output.ts(5,20): error TS2307: Cannot find module 'immutable'.
src/Output.ts(712,33): error TS7006: Parameter 'row' implicitly has an 'any' type.
src/Output.ts(714,32): error TS7006: Parameter 'char' implicitly has an 'any' type.
src/Output.ts(828,17): error TS7006: Parameter 'row' implicitly has an 'any' type.
src/PTY.ts(4,22): error TS2307: Cannot find module 'node-pty'.
src/references.d.ts(9,1): error TS6053: File '/home/br/Downloads/upterm/node_modules/immutable/dist/immutable.d.ts' not found.
src/views/OutputComponent.tsx(6,20): error TS2307: Cannot find module 'immutable'.
src/views/OutputComponent.tsx(103,38): error TS7006: Parameter 'possiblyEmptyRow' implicitly has an 'any' type.

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/home/br/.nvm/versions/node/v8.1.3/bin/node" "/home/br/Downloads/upterm/node_modules/.bin/npm" "run" "tsc"
npm ERR! node v8.1.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! upterm@0.2.158 tsc: `tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the upterm@0.2.158 tsc script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the upterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs upterm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls upterm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/br/Downloads/upterm/npm-debug.log

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/home/br/.nvm/versions/node/v8.1.3/bin/node" "/home/br/Downloads/upterm/node_modules/.bin/npm" "run" "compile"
npm ERR! node v8.1.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! upterm@0.2.158 compile: `npm run cleanup && npm run tsc && npm run copy-html`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the upterm@0.2.158 compile script 'npm run cleanup && npm run tsc && npm run copy-html'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the upterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run cleanup && npm run tsc && npm run copy-html
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs upterm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls upterm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/br/Downloads/upterm/npm-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! upterm@0.2.158 pack: `npm run compile && build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the upterm@0.2.158 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/br/.npm/_logs/2017-06-30T04_40_34_812Z-debug.log
```

log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/br/.nvm/versions/node/v8.1.3/bin/node',
1 verbose cli   '/home/br/.nvm/versions/node/v8.1.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'pack' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose run-script [ 'prepack', 'pack', 'postpack' ]
5 info lifecycle upterm@0.2.158~prepack: upterm@0.2.158
6 silly lifecycle upterm@0.2.158~prepack: no script for prepack, continuing
7 info lifecycle upterm@0.2.158~pack: upterm@0.2.158
8 verbose lifecycle upterm@0.2.158~pack: unsafe-perm in lifecycle true
9 verbose lifecycle upterm@0.2.158~pack: PATH: /home/br/.nvm/versions/node/v8.1.3/lib/node_modules/npm/bin/node-gyp-bin:/home/br/Downloads/upterm/node_modules/.bin:/home/br/.nvm/versions/node/v8.1.3/bin:/home/linuxbrew/.linuxbrew/sbin:/home/br/perl5/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/br/perl5/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle upterm@0.2.158~pack: CWD: /home/br/Downloads/upterm
11 silly lifecycle upterm@0.2.158~pack: Args: [ '-c', 'npm run compile && build' ]
12 silly lifecycle upterm@0.2.158~pack: Returned: code: 1  signal: null
13 info lifecycle upterm@0.2.158~pack: Failed to exec pack script
14 verbose stack Error: upterm@0.2.158 pack: `npm run compile && build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/br/.nvm/versions/node/v8.1.3/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/br/.nvm/versions/node/v8.1.3/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid upterm@0.2.158
16 verbose cwd /home/br/Downloads/upterm
17 verbose Linux 4.4.0-81-generic
18 verbose argv "/home/br/.nvm/versions/node/v8.1.3/bin/node" "/home/br/.nvm/versions/node/v8.1.3/bin/npm" "run" "pack"
19 verbose node v8.1.3
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error upterm@0.2.158 pack: `npm run compile && build`
23 error Exit status 1
24 error Failed at the upterm@0.2.158 pack script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by lnpalmer** [comment]
+1 on vanilla Ubuntu 16.04

**Comment by neolectron** [comment]
+1 on vanilla debian9

**Comment by ifzm** [comment]
+1 on vanilla Ubuntu 16.04

**Comment by nicolo-ribaudo** [comment]
I think this is an issue with npm: if I use yarn I can build upterm without any error

**Comment by benjamin-rood** [comment]
@nicolo-ribaudo 
`yarn install` works, but I also fail at `yarn run pack`:

```
❯ yarn run pack
yarn run v0.27.5
$ npm run compile && build
/home/br/Downloads/upterm/node_modules/npm/node_modules/npmlog/log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (/home/br/Downloads/upterm/node_modules/npm/node_modules/npmlog/log.js:57:33)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /home/br/Downloads/upterm/node_modules/npm/bin/npm-cli.js:19:13
    at Object.<anonymous> (/home/br/Downloads/upterm/node_modules/npm/bin/npm-cli.js:75:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I have an almost identical issue if I use `npm run pack`:

```
 npm run pack

> upterm@0.2.158 pack /home/br/Downloads/upterm
> npm run compile && build

/home/br/Downloads/upterm/node_modules/npm/node_modules/npmlog/log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (/home/br/Downloads/upterm/node_modules/npm/node_modules/npmlog/log.js:57:33)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /home/br/Downloads/upterm/node_modules/npm/bin/npm-cli.js:19:13
    at Object.<anonymous> (/home/br/Downloads/upterm/node_modules/npm/bin/npm-cli.js:75:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! upterm@0.2.158 pack: `npm run compile && build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the upterm@0.2.158 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/br/.npm/_logs/2017-07-10T22_11_17_302Z-debug.log
```

**Comment by jmhibben** [comment]
+1 Can confirm build issues on Linux Mint 18.1 as well. Errors are approximately what @benjamin-rood is seeing, but both `npm install` and `yarn install` fail.

Here are pastebins for both the [yarn install](https://pastebin.com/EKRMrpi2) and [npm install](https://pastebin.com/yw9cLcNU) errors.

Specs:
> npm v5.0.4
> node v8.1.3
> yarn 0.27.5
> Linux Mint 18.1 Cinnamon Edition

**Comment by vlad-shatskyi** [comment]
Does it work now? Please try to remove `node_modules` before executing `npm install`.

**Comment by jmhibben** [comment]
@vlad-shatskyi I completely removed and re-cloned the source to give myself a fresh start. Running both commands succeeded for me, though (weirdly) I also needed to install g++. Apparently Linux Mint only ships with gcc and not g++.

**Comment by fpoumian** [comment]
I was unable to run the "pack" task successfully with NPM (Ubuntu 16.04), but I was able to run it with Yarn.

**Comment by fpoumian** [comment]
I'm also having similar issues trying to run ` npm run pack` in Ubuntu 16.04, but with different output:
`> upterm@0.2.160 pack /home/fpoumian/.local/share/upterm
> npm run compile && build


> upterm@0.2.160 compile /home/fpoumian/.local/share/upterm
> npm run cleanup && npm run tsc && npm run copy-html


> upterm@0.2.160 cleanup /home/fpoumian/.local/share/upterm
> rimraf compiled/src


> upterm@0.2.160 tsc /home/fpoumian/.local/share/upterm
> tsc


> upterm@0.2.160 copy-html /home/fpoumian/.local/share/upterm
> mkdirp compiled/src/views && cpx src/views/index.html compiled/src/views

electron-builder 19.13.0
electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
Rebuilding native production dependencies for linux:x64
Error: spawn /home/ubuntu/local/node ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at spawn (/home/fpoumian/.local/share/upterm/node_modules/electron-builder-util/src/util.ts:101:3)
    at /home/fpoumian/.local/share/upterm/node_modules/electron-builder/src/util/yarn.ts:141:5
From previous event:
    at rebuild (/home/fpoumian/.local/share/upterm/node_modules/electron-builder/out/util/yarn.js:95:22)
    at /home/fpoumian/.local/share/upterm/node_modules/electron-builder/src/util/yarn.ts:16:11
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at installOrRebuild (/home/fpoumian/.local/share/upterm/node_modules/electron-builder/out/util/yarn.js:34:21)
    at /home/fpoumian/.local/share/upterm/node_modules/electron-builder/src/packager.ts:306:13
    at next (native)
From previous event:
    at Packager.installAppDependencies (/home/fpoumian/.local/share/upterm/node_modules/electron-builder/out/packager.js:360:11)
    at /home/fpoumian/.local/share/upterm/node_modules/electron-builder/src/packager.ts:204:20
    at next (native)
From previous event:
    at Packager.doBuild (/home/fpoumian/.local/share/upterm/node_modules/electron-builder/out/packager.js:303:11)
    at /home/fpoumian/.local/share/upterm/node_modules/electron-builder/src/packager.ts:161:52
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/home/fpoumian/.local/share/upterm/node_modules/electron-builder/out/packager.js:222:11)
    at /home/fpoumian/.local/share/upterm/node_modules/electron-builder/src/builder.ts:256:40
    at next (native)
From previous event:
    at build (/home/fpoumian/.local/share/upterm/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/home/fpoumian/.local/share/upterm/node_modules/electron-builder/src/cli/cli.ts:41:4)
    at Object.self.runCommand (/home/fpoumian/.local/share/upterm/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/home/fpoumian/.local/share/upterm/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/home/fpoumian/.local/share/upterm/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/home/fpoumian/.local/share/upterm/node_modules/electron-builder/src/cli/cli.ts:36:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

┌────────────────────────────────────────────────────────────┐
│            electron-builder update check failed            │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) /home/fpoumian/.config │
└────────────────────────────────────────────────────────────┘

npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/home/fpoumian/.nvm/versions/node/v6.9.1/bin/node" "/home/fpoumian/.nvm/versions/node/v6.9.1/bin/npm" "run" "pack"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! upterm@0.2.160 pack: `npm run compile && build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the upterm@0.2.160 pack script 'npm run compile && build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the upterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile && build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs upterm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls upterm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fpoumian/.local/share/upterm/npm-debug.log
`
Not sure why is trying to find node at `/home/ubuntu/local/node`; my NODE_PATH is `/home/fpoumian/.nvm/versions/node/v6.9.1/bin/node`

**Comment by benjamin-rood** [comment]
@vlad-shatskyi 
`npm install` no longer produces errors, but it does not actually install anything. There is no "dist" directory. All that `npm pack` does is build `upterm-0.2.160.tgz` which is just a tar'd and gzipped version of the repository. Utterly useless.

To use this, I either need to get a `*.deb` which I can install, or a binary which I can put in  `/usr/bin` or some equivalent.

As I'm sure you are aware, I'm able to install upterm perfectly on macOS through brew, it's just a shame I can't use linuxbrew. I fully understand that this is free software and a 0.* version as well, so I'm sorry if this sounds grumpy or ungrateful. Please just tell me what information I can give you to make this work.

**Comment by jmhibben** [comment]
@fpoumian
Strange that my build succeeded when yours didn't. Have you tried building with different versions of node? Mine went perfectly with v8.1.3.

@benjamin-rood
The command you ran, `npm pack`, did exactly what it's intended to do, and should _not_ be confused with `npm run pack`. The former command runs npm's built-in `pack`. The latter, which is what you should be running, executes the package's `pack` script.

As a side note, `npm install` does _not_ install the program - it simply installs the program's dependencies. It's an easy thing to misinterpret, unfortunately.

**Comment by fpoumian** [comment]
Nevermind, turns out that my `$NODE_PATH` variable was correct, but my `$NODE` variable was pointing to the wrong place, and the `electron-builder` was referencing that `$NODE` var to spawn a child process. This can be easily fixed by adding this line to `~/.basrch`:

```bash
export NODE=`which node`
```

**Comment by benjamin-rood** [comment]
@jmhibben D'oh thanks for clarifying!

**Comment by vlad-shatskyi** [comment]
Now we have official linux images, so you don't need to build it yourself anymore. https://github.com/railsware/upterm/releases

**Comment by benjamin-rood** [comment]
@vlad-shatskyi Much appreciated, thank you!
