### ISSUE TITLE
Stick Prompt to the Bottom

### ISSUE THREAD

**Issue by vlad-shatskyi** [railsware/upterm#1106]
- **#benefit** Easier to switch focus to the statusbar.
- **#benefit** It's at the bottom most of the time anyway after you type a few commands. In this position the first autocomplete item is far from the eyes. If prompt was always at the bottom, we could revert suggestions upside down (as in fzf).
- **#benefit** Simplifies autocompletion box positioning.
- **#risk** Different from what people are used too. Some might dislike it.

**Comment by vlad-shatskyi** [comment]
Prototype: https://github.com/railsware/upterm/tree/experiment-stick-prompt

**Comment by gritt** [comment]
Hi @vlad-shatskyi 

Is there any way to disable this feature? I'm really used to clear the terminal frequently or just hitting enters to split things, and this behaviour kinda breaks it, I can't currently clear the screen; also I do prefer to see the results of my commands appearing below it;
