### ISSUE TITLE
Build in Docker Container

### ISSUE THREAD

**Issue by vlad-shatskyi** [railsware/upterm#1108]

**Comment by beardedfoo** [comment]
@vlad-shatskyi would you mind if I worked on this issue? I've been looking for a way I can contribute to upterm and I think I could tackle this.

**Comment by vlad-shatskyi** [comment]
@beardedfoo I'd love that!

So, the requirement is that I clone the repo, run a docker command, and get a Linux package (produced by `npm run pack`) on my host computer in the `dist/` directory. It solves the issues with dependencies management (like libreadline.so.6). It would be nice to have builds for either OS X or Linux, if `electron-builder` supports building OS X packages on Linux.

**Comment by vlad-shatskyi** [comment]
Maybe you also have some ideas how to start the develoment version (`npm start`) in a container and then use it on the host?

**Comment by vlad-shatskyi** [comment]
@beardedfoo do you still want to work on this?

**Comment by vlad-shatskyi** [comment]
@beardedfoo I'll assume you changed your mind and will assign this to myself. Just wanted to let you know in order not to step on each other toes, if you're working on it.

**Comment by vlad-shatskyi** [comment]
A container would help avoid issues like this: https://github.com/railsware/upterm/issues/1110
