### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by black-snow** [railsware/upterm#1113]
There's no way to change the font size in ther terminal, right? At least not via the UI.

**Comment by vlad-shatskyi** [comment]
@black-snow that's correct; it's not there yet. Although, there is an open issue already, so I'll close this one. Please make sure to vote for that issue if you want to see it implemented sooner. https://github.com/railsware/upterm/issues/1113

**Comment by black-snow** [comment]
Weird that the search didn't show me that issue ... thanks.

**Comment by vlad-shatskyi** [comment]
@black-snow now you can change font size with <kbd>Cmd</kbd>+<kbd>+</kbd> and  <kbd>Cmd</kbd>+<kbd>-</kbd>. Or  <kbd>Ctrl</kbd>, if you use Linux.

**Comment by black-snow** [comment]
Awesome!
Which version ships this? Not working in 0.2.161

**Comment by vlad-shatskyi** [comment]
It's not released yet, but you can clone the repo and run `npm run pack`. Or wait for a few days for a new release.

**Comment by black-snow** [comment]
Aight, thanks

**Comment by vlad-shatskyi** [comment]
May I ask you a few questions about your experience with Upterm?

**Comment by black-snow** [comment]
Of course. Feel free to mail me @ info at black-snow.net

**Comment by vlad-shatskyi** [comment]
There is nothing private, so I'll ask here. If you don't feel like answering them in public my email is shockone89@gmail.com.

1. What made you switch to Upterm?
2. Is there anything that annoys you?
3. What features do you miss?
4. How did you find Upterm?

**Comment by black-snow** [comment]
1. Actually I haven't fully switched to upterm. I use the default OS X terminal, my IDE/editor's integrated terminal and upterm at the same time (silly, isn't it?). But let me tell you what I find great about upterm:
1.1 Current path shown in the bottom (awesome!)
1.2 Tooltips and notifications (nice!)
1.3 Colors (bg color)
1.4 Search
1.5 Showing me the git branch? Just recognized that. F*ck yeah.
2. Somewhat.
2.1 Search results get lost when something's happening in the terminal.
2.2 Confused when first starting upterm for it's just showing a blank window. Wait, this is a terminal, right? Why isn't there a cursor in the top left? Maybe we could show some text instead of an empty background? (As it's done in Atom.)
2.3 Background color sometimes confusing. I guess it's always red when the exit code wasn't 0? Some programs I use usually don't exit with 0 / are throwing some hints and warnings but nothin critical. Always takes me a second look cuz I think something's gone badly wrong due to the red punching me in the face.
2.4 Updates from within the app would be nice. (instead of brew cask reinstall upterm)
2.5 Font size (already addressed)
2.6 No "about upterm" in the menu. That's ... uncommon.
2.7 Sometime's focus seems gone on the input but when I type it actually goes in there. That's weird.
2.8 Why can't I `cd $SOMEVAR`? I have some shortcuts for common paths like `$HT` for my htdocs. I commonly `cd $HT` but that's not working in upterm ... `echo $HT` does echo the contents just right.
3. ->
3.1 Having an "edit .bashrc" and "edit .ssh/config" etc. in the menu would be a nice shortcut.
3.2 No titles for the tabs. That's actually annoying. I don't remember which tab's what. At least let me rightclick + set a title.
3.3 Also it's hard to see which tab is active. More contrast or some other indicator please!
3.4 It'd be sweet if I could click the branch icon (git) to switch it (visually).
4. Don't remember. Probably https://github.com/sindresorhus/awesome-electron

Also there's this:
```
(node:4092) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
process.on @ internal/process/warning.js:21
```

**Comment by vlad-shatskyi** [comment]
Wow, that's a great feedback, @black-snow, thank you so much! We already have open issues for some of your concerns, but I'll make sure to create ones for the rest. Also, updates within the app are already implemented, you'll see a notification when the next version is released.
