### ISSUE TITLE
I get couple of hundred thousands of  ENOSPC errors upon startup

### ISSUE THREAD

**Issue by capaj** [railsware/upterm#1130]
I just installed on ubuntu 17.04 and I get this:

![image](https://user-images.githubusercontent.com/1305378/28366359-a1bbdab8-6c8c-11e7-8aef-144510730dd7.png)

ENOSPC is probably because my file descriptor limit is reached. I think this could be caused by my whole home directory being a git directory and upterm is trying to watch it.

It would make sense to catch this error and handle it so that it doesn't freeze the whole app.

**Comment by vlad-shatskyi** [comment]
@capaj, thanks for reporting! Could you please check if the version in master works for you?

**Comment by capaj** [comment]
@vlad-shatskyi yes, it doesn't freeze now. I still get several of these errors on startup:

![image](https://user-images.githubusercontent.com/1305378/28439671-230a066e-6da3-11e7-8f4c-35bbbeb6b445.png)

but that is something else. I'll create another issue for that. Thanks @vlad-shatskyi !
