### ISSUE TITLE
Terminal width is not detected correctly in a split.

### ISSUE THREAD

**Issue by BlitzKraft** [railsware/upterm#1138]
![Output of ls](https://user-images.githubusercontent.com/6516167/28655321-e014fc72-724f-11e7-9e1a-4727cca1eb82.png)
![typing a long command](https://user-images.githubusercontent.com/6516167/28655456-fe5c1f7a-7250-11e7-8012-130ce2db9134.png)

![vim in one pane](https://user-images.githubusercontent.com/6516167/28655490-2cabb8ea-7251-11e7-9113-63a24ce51a73.png)

Steps to reproduce: 

 1. Start upterm
 2. Select split vertically from the menu
 3. Use `ls` or any other command with full width output.

There is no output in the console. Seems like an issue with the view. The terminal behaves as if the width is 225 columns, but displays it in half the width. The

**Comment by vlad-shatskyi** [comment]
Thanks for reporting @BlitzKraft.

**Comment by BlitzKraft** [comment]
I can't seem to have more than one extra split. Is this expected? I am on https://github.com/railsware/upterm/commit/184c9244e365a1334431cf939a17b9ee55ebcade

**Comment by vlad-shatskyi** [comment]
@BlitzKraft yes, that's intended. A tab can have either one session or two sessions side by side. No recursive nesting.
