### ISSUE TITLE
Upterm fails to install

### ISSUE THREAD

**Issue by rbingham** [railsware/upterm#1154]
When trying to install upterm it fails to install with:

```
error: failed to commit transaction (conflicting files)
electron: /usr/bin/electron exists in filesystem
Errors occurred, no packages were upgraded.
==> ERROR: 'pacman' failed to install missing dependencies.
:: failed to build upterm package(s)
```

OS: Arch linux

It looks like it fails because I already have electron installed (through npm)

**Comment by vlad-shatskyi** [comment]
Hey, @rbingham. The AUR package isn't officially supported, you can download the latest release from this place: https://github.com/railsware/upterm/releases

Although, just removing electron before installing upterm should help.
