### ISSUE TITLE
Tab Completion on mutli directory paths with spaces

### ISSUE THREAD

**Issue by saphid** [railsware/upterm#1163]
Folder structure:
~/Box Sync/Alex Southwell

Commands run:
cd ~/B<tab>
Becomes:
cd ~/Box\ Sync/
Continue:
cd ~/Box\ Sync/A<tab>
Becomes:
cd ~/Box Sync/Alex\ Southwell

Last tab completion loses the first escaped space
"~/Box\ Sync/" Becomes "~/Box Sync/"

**Comment by sorousht** [comment]
@vlad-shatskyi I pick this one

**Comment by vlad-shatskyi** [comment]
Hey, @sorousht. Do you still want to work on this?

**Comment by sorousht** [comment]
Hey, @vlad-shatskyi Sorry, I was busy this week, but I'm currently working on the issue :-)

**Comment by sorousht** [comment]
@vlad-shatskyi So far, I've tried to fix the problem by escaping `tokenDirectory` in src/plugins/autocompletion_utils/Common.ts [line: 170], but It causes some problem in suggestions! Do you have any hint?

**Comment by vlad-shatskyi** [comment]
Fixed.
