### ISSUE TITLE
No explanation for how to use with rvm

### ISSUE THREAD

**Issue by snood1205** [railsware/upterm#1164]
I've been trying to use upterm and on the whole it's fine, but with `irb` or `pry` I get 

> Upterm: command "bundled_irb" not found.                                                              

or 

> Upterm: command "bundled_pry" not found.                                                              

When I type `which irb` in upterm I get `/Users/<USERNAME>/.rvm/rubies/ruby-2.4.1/bin/irb` and then I run that and it works so I'm not exactly sure what's going on with irb or pry here.

**Comment by vlad-shatskyi** [comment]
@snood1205 why did you close it? Was it something on your end?

**Comment by snood1205** [comment]
@vlad-shatskyi Yeah. I had messed up my path. It wasn't an issue on your end.
