### ISSUE TITLE
Pressing tab will autocomplete from history instead of trying folder first

### ISSUE THREAD

**Issue by koressak** [railsware/upterm#1181]
Currently, when you have some historical movements between folders, the upterm will show them and use them firstly before trying to autocomplete with the current subfolders.

For example - structure of a folder:
work/
 - company1/
   - project2
 - company2
 - company3/
   - project1

When I went to a company3 folder sometime ago, upterm will for all time try to complete my command: cd work/"press tab key" with company3 and full project1 folder.

But that's kind of uncomfortable, because whenever I need to go to company1 or company2 I have to choose manually with arrow keys the proper directory. Thus saving me no time, even adds a little bit of frustration when trying to get somewhere fast :)

**Comment by vlad-shatskyi** [comment]
What version do you use, @koressak? It should be fixed in https://github.com/railsware/upterm/releases/tag/v0.4.0

**Comment by koressak** [comment]
Well, today I installed the new version 0.4 via brew cask, but even if I turned the upterm off and on again, it did not help.

Something I do the wrong way? Clear cache somehow?

**Comment by koressak** [comment]
I'm sorry, even though it seemed it installed the 0.4 version, it did not. So thank you for the response, ignore this thread :)
