### ISSUE TITLE
git autocomplete not working.

### ISSUE THREAD

**Issue by JWesorick** [railsware/upterm#1184]
Looking at the source it looks like I should be getting autocomplete suggestions with git commands. Right now I am getting none. Latest from Homebrew. Can't figure out how to check the version.

**Comment by vlad-shatskyi** [comment]
Hey, @JWesorick. I'm having a similar issue; try this: type `git checkout ` (with a space at the end) and wait for a few seconds. Does it appear eventually?

**Comment by vlad-shatskyi** [comment]
It should work in master now. Could you try it, please?

**Comment by JWesorick** [comment]
Sorry. Still noting. Not even after waiting. I have the latest from master. (e778fc4a2e is the last comit)

![aug-30-2017 09-32-28](https://user-images.githubusercontent.com/801062/29874948-56be9276-8d66-11e7-8296-1b03b20d14e2.gif)

**Comment by vlad-shatskyi** [comment]
Could you please open developer tools and see if there are any errors? Also, do you have some aliases for git?

**Comment by vlad-shatskyi** [comment]
Ah, I see t now in you completion. You have an alias git to hub. And we don't support completion for hub at the moment.

**Comment by JWesorick** [comment]
yep. Didn't even realize I had that installed. Thanks!
