### ISSUE TITLE
Strange shell name @ screenfetch 👀

### ISSUE THREAD

**Issue by artkirienko** [railsware/upterm#1187]
**AT FIRST I WAS LIKE BUT THEN I WAS LIKE**

<img width="682" alt="iterm" src="https://user-images.githubusercontent.com/2473081/29914599-c7a42c90-8e41-11e7-800f-938ec9938a34.png">

**BUT THEN I**

![upterm](https://user-images.githubusercontent.com/2473081/29914605-cc26be36-8e41-11e7-9feb-a9fca48ea7b0.png)

😂

**Comment by vlad-shatskyi** [comment]
Probably this program determines `$SHELL` in some non-standard way. I'll close this issue as it doesn't affect any real use-cases.
