### ISSUE TITLE
Can´t compile

### ISSUE THREAD

**Issue by JPRuehmann** [railsware/upterm#1189]
Hello
I get the following error.
If I enter
`npm prune`
I get
`npm ERR! Cannot read property 'find' of undefined`
How can I make it work?
I am using Kubuntu 16.04 LTS
Thanks,

**Comment by vlad-shatskyi** [comment]
Please make sure you use the latest `node` and `npm` version.

**Comment by JPRuehmann** [comment]
Thanks
I do that Atom works fine with it
upterm compiles but can´t create any packages but I can copy the compiled files by Hand.
I will add my skript.
[update_upterm.txt](https://github.com/railsware/upterm/files/1362429/update_upterm.txt)
