### ISSUE TITLE
Switching tab causes different viewpoint in window (I have to scroll down every time)

### ISSUE THREAD

**Issue by rvanmarkus** [railsware/upterm#1197]
When switching between multiple tabs the window viewpoint changes after a click (or using a shortcut key), and the latest output isn't visible anymore. So every time opening an existing tab causes the user to scroll down to see the latest output. Something that becomes a bit annoying after a while, and definitely affects the user experience/productivity. 

Example:
https://cl.ly/2j0h2i1q2z2C

I would like to make some time somewhere next week (or maybe earlier) to maybe search if I can find the bug either fix it.

**Comment by vlad-shatskyi** [comment]
You have an outdated version. Please download the latest one, where it's already fixed. https://github.com/railsware/upterm/releases/tag/v0.4.0
