### ISSUE TITLE
Autocompletion stopped working for 'git checkout' on MacOS

### ISSUE THREAD

**Issue by marklackey** [railsware/upterm#1227]
Just downloaded the latest version, and I no longer have autocompletion when I use git with the checkout command.

**Comment by vlad-shatskyi** [comment]
Please open developer tools and see if you have any errors.
![image](https://user-images.githubusercontent.com/188928/30764647-94c7b6ce-9ff4-11e7-822a-d857fb7f05c2.png)

**Comment by marklackey** [comment]
I did have an error that said I had to accept the xcode license. with a 'sudo' command. i'm sorry i wasn't able to copy and paste the error for you, but once i accepted the license, the functionality returned. so it seems like somehow with this release there was a need for something to be compiled.

**Comment by vlad-shatskyi** [comment]
@marklackey maybe you updated xcode recently?

**Comment by marklackey** [comment]
Yeah, I hadn't noticed, but apparently xcode was automatically updated. Thanks for building a great app!
