### ISSUE TITLE
pasting multi line commands into upterm and terminal , #should

### ISSUE THREAD

**Issue by slash** [railsware/upterm#1235]
so it kinda should just work ?
<img width="1920" alt="downloads -bash 100x26 2017-09-24 20-33-30" src="https://user-images.githubusercontent.com/15662/30785497-c3f8ed86-a167-11e7-812f-97a8a850204f.png">

**Comment by vlad-shatskyi** [comment]
Won't implement; this can be a source of security issues. ZSH has the same behavior as Upterm.
