### ISSUE TITLE
Please fix it.

### ISSUE THREAD

**Issue by JamesLinus** [railsware/upterm#1271]
When I run the 'clear' Unix command. The middle Display window does not change. Please fix it.

**Comment by AtomicCoding** [comment]
@JamesLinus 
What do you mean by Middle Display Window? 
Please provide more info or screenshots and try to make the title more descrptive than just `Please fix it.`. Something like, `Problems with clearing upterm` would be better.

**Comment by rootasjey** [comment]
If this issue has not been updated with more clarity, it should be closed 🙂

**Comment by le0pard** [comment]
ok, lets close it
