### ISSUE TITLE
After the installation, direct use, no prompt for the command? Does it need to be configured?

### ISSUE THREAD

**Issue by flyweights** [railsware/upterm#1279]
After the installation, direct use, no prompt for the command? Does it need to be configured?

**Comment by flyweights** [comment]
It just doesn't work as TAB

**Comment by flyweights** [comment]
ctrl + space => no suggestions

**Comment by rootasjey** [comment]
It should work normally after installation. 

* Can you open the 'Dev Tools' and tell us if there's any error ?
* Are you able to type and execute a command ?
* Are you talking about auto-completion suggestions ?

**Comment by flyweights** [comment]
之后，莫名其妙就可以了。我不知道是什么原因，可能是我升级系统了。

**Comment by flyweights** [comment]
After that, it's ok. I don't know why. Maybe I upgraded the system.

**Comment by rootasjey** [comment]
Alright. So this issue can be closed then 🙂
