### ISSUE TITLE
When multiple tabs are open, enter key no longer works due to Invalid array length

### ISSUE THREAD

**Issue by humanly-clement** [railsware/upterm#1289]
Tried on version 0.4.3, 0.4.2, and 0.3.2 so far.

When there are multiple tabs open, I cannot execute any commands. I have to completely restart the application to get it working again.

![screen shot 2018-03-03 at 2 20 21 pm](https://user-images.githubusercontent.com/34407518/36928823-3de176aa-1eee-11e8-8915-9baa0e710300.png)

**Comment by rootasjey** [comment]
I can't reproduce this error. I've 3 tabs opened and I can still execute commands like `>ls`.
I'm on version 0.4.4 through.
Could try on the latest version and describe how to reproduce this error ?
![screen shot 2018-06-03 at 14 00 39](https://user-images.githubusercontent.com/5097282/40886357-9cb12cf8-6736-11e8-9a4a-e1aad0df3f64.png)

**Comment by clemnz** [comment]
Hey @rootasjey, I can't seem to reproduce this error on 0.4.4 as well =)

**Comment by rootasjey** [comment]
Okay. Yes we can close it for now, except if someone knows how to reproduce it :)
(I don't have the right to close it though ^^)

**Comment by le0pard** [comment]
Ok, closed
