### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by achikin** [railsware/upterm#1300]
I don't see any recent activity and the latest release is of september 2017. Is this project abandoned?

**Comment by le0pard** [comment]
Hello, @achikin 

https://github.com/railsware/upterm/issues/1288#issuecomment-366338113

This is reason. I am working to support it, but I don't have vision for it. Company will search for new major contributor(s). This will be announced soon.

**Comment by le0pard** [comment]
Also, you are wrong about activity: 
![image](https://user-images.githubusercontent.com/98444/40590013-961d258a-6200-11e8-8b78-a121f965444c.png)

**Comment by achikin** [comment]
@le0pard I judge by releases, not by the latest commit.

**Comment by le0pard** [comment]
@achikin ok, but

> I don't see any recent activity and the latest release is of september 2017.

in this case your words "don't see any recent activity" == "the latest release is of september 2017", because you measure activity be releases.

**Comment by le0pard** [comment]
Published https://github.com/railsware/upterm/issues/1301
