### ISSUE TITLE
Let applications use webview

### ISSUE THREAD

**Issue by doesntgolf** [railsware/upterm#267]
So that we could have terminal-based web browsers in this web browser-based terminal. ("Full" browser rather than a text browser.)

And also developers could build TUIs with html/css/js similar to how they'd use ncurses.

**Comment by vlad-shatskyi** [comment]
Won't implement. It would mean that certain applications could only be used in upterm. Instead the current vision is to output JSON and create a prettifier plugin which can transform that JSON to whatever React component.
