### ISSUE TITLE
Small issue with cache location on linux and an error when trying to set it.

### ISSUE THREAD

**Issue by ar-qun** [railsware/upterm#293]
Disclaimer: I am a newbie in electron.

When I try to add:

`app.setPath('cache', '/tmp')`

I get this error:

```
app.setPath('cache', '/tmp');
               ~~~~~~~

src/main/Main.ts(12,13): error TS2345: Argument of type '"cache"' is not assignable to parameter of type '"home" | "appData" | "userData" | "temp" | "exe" | "module" | "desktop" | "documents" | "download...'.

```

I tried this line in a clean electron project and there is no error.

Also if I am not wrong, cache is stored at the same folder where configuration is. Should it not be in .cache(on linux)? It's also impossible to change.

**Comment by shockone** [comment]
But there is nothing related to cache on line 12. https://github.com/shockone/black-screen/blob/master/src/main/Main.ts#L12

**Comment by ar-qun** [comment]
I am adding this line just before current line #12.

**Comment by shockone** [comment]
According to the documentation, you can override paths only for certain names. That's exactly what error says: 'cache' is not allowed there. https://github.com/electron/electron/blob/master/docs/api/app.md#appsetpathname-path

**Comment by ar-qun** [comment]
The code for cache is there https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_app.cc#L86 and it works. I did some quick test [here](https://github.com/ar-qun/electron-quick-start/blob/master/main.js#L7) and it works just fine. 

That's why it is so strange. Can it be because `const app`?

**Comment by shockone** [comment]
@ar-qun it's because the declared type of this parameter doesn't match the argument. Now, in order to convince the compiler that you can put it there you can do two things:

* Cast it to `any`: `app.setPath(<any>'cache', '/tmp');`
* Augment the definition of `AppPathName`. You'd have to open a PR to change this line: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/github-electron/github-electron.d.ts#L315

**Comment by ar-qun** [comment]
Thanks,

I think I need to dig a little bit more. I only just started and I need to process all this information before I can express it coherently.

So as far as I understand it is TypeScript related staff right? Because I have few electron applications and they so far(Nylas for example) use cache related parameters right.

Will get it to DefinitelyTyped then.

Thanks for your time! Love your project.
