### ISSUE TITLE
scroll bug in man pages

### ISSUE THREAD

**Issue by bj7** [railsware/upterm#304]
Hello, I believe I have found a bug with scrolling in the man pages. I couldn't find it reported anywhere, but if you open a man page and hit `enter`, the `:` position marker drops down but the screen does not scroll with it, and you cannot scroll to follow the `:` and see the rest of the man page. 

If this is not an exceptionally hard bug (as per the markings you have given other issues) I would love to take a crack at this in my spare time.

**Comment by shockone** [comment]
Here's what I see after hitting enter a few times. Do you see something different?

![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/jk60-xwt.png)

**Comment by bj7** [comment]
Yes, my `:` disappears off screen and does not follow the scroll, and I'm not sure of why everything is underlined? 

![image](https://cloud.githubusercontent.com/assets/1395096/15072640/004df7ee-1362-11e6-9eee-c7e7a54acaca.png)

**Comment by vlad-shatskyi** [comment]
Fixed.
