### ISSUE TITLE
Feature: Git Timeline Pop up

### ISSUE THREAD

**Issue by dimitrieh** [railsware/upterm#355]
This project is awesome! Big fan of iterm2 here btw.. wonder how this compares or will compare in the future... work together?

feature proposal: when clicking this button:

![image](https://cloud.githubusercontent.com/assets/429659/15454828/6af2ef6c-2043-11e6-9e51-40f39673c82d.png)

See the following split the screen (ps git timeline view taken from [gitkraken](https://www.gitkraken.com)): 

![image](https://cloud.githubusercontent.com/assets/429659/15454870/73c3636e-2044-11e6-8cb9-ebbd687b6cac.png)

**Comment by shockone** [comment]
I'm not sure we should display log on click (the other option would be to display branches and allow to switch between them), but you can display this as an output of `git log` or whatever by writing an output decorator. It's pretty easy, all you need to do is to return a React element with whatever you want to be inside. Here's an example: https://github.com/shockone/black-screen/blob/master/src/plugins/GitDiff.tsx
