### ISSUE TITLE
Bash startup

### ISSUE THREAD

**Issue by genxstylez** [railsware/upterm#422]
Hi, I am new to this project, this question mught be a real noobie one.

Which bash startup file is it using?

**Comment by shockone** [comment]
Both `~/.bashrc` and `~/.bash_profile`, @genxstylez. But only to import aliases.

**Comment by genxstylez** [comment]
@shockone that means I can't use [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/install.html)?
with the following startup script?
```
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh
```

**Comment by jwhitmarsh** [comment]
I've put echos and aliases in ~/.bashrc and ~/.bash_profile and it doesn't look like either are being loaded in v0.2.55 (see working comparison with iTerm2)

![screen shot 2016-09-28 at 08 51 18](https://cloud.githubusercontent.com/assets/8026009/18904978/c65a5c58-8558-11e6-94f4-cbbc6c1cc9f3.png)

![sep-28-2016 08-52-43](https://cloud.githubusercontent.com/assets/8026009/18905025/f743d4ca-8558-11e6-87e1-4bb9c6b76aaa.gif)

**Comment by drew-gross** [comment]
Are you launching Black Screen via zsh by any chance, or do you have zsh installed? Are there any errors in the console? You can see them with Command+Alt+i

**Comment by vlad-shatskyi** [comment]
We only extract aliases from those files. Everything else - including `echo` statements - is ignored.
