### ISSUE TITLE
Scrolling up in less produces weird results

### ISSUE THREAD

**Issue by ashkitten** [railsware/upterm#556]
steps:
$ less README.md
[scroll down]
[scroll back up]
wtf

![screenshot from 2016-07-05 16-04-06](https://cloud.githubusercontent.com/assets/9281956/16598070/1ffdc06e-42ca-11e6-9063-8d6868fc3bdf.png)

**Comment by shockone** [comment]
Confirmed. Likely related to the recent changes in https://github.com/shockone/black-screen/commit/c037198bb7eb1882dbb3d4ba6d57fb34bd69904e

**Comment by brendanlong** [comment]
I'm not sure if this is related, but `less` is completely broken for me. For example, `aws s3 help`:

<img width="885" alt="screen shot 2017-01-31 at 1 17 05 pm" src="https://cloud.githubusercontent.com/assets/1447206/22478387/9f40d14e-e7b7-11e6-9a26-a2e8efdbf149.png">

**Comment by vlad-shatskyi** [comment]
Fixed.
