### ISSUE TITLE
[cmd + k] Clear screen with a shortcut

### ISSUE THREAD

**Issue by darol100** [railsware/upterm#577]
### Problem / Motivation

In Mac there is the ability of clear the screen by using the `cmd + k`.  In ubuntu, the shortcut is `ctrl + l`.
### Solution

Add the ability of clearing the screen with `cmd + k`. This shortcut is the same as the command `clear`.

**Comment by ChrisButterworth** [comment]
`ctrl + l` clears terminal and works in black screen

**Comment by luco** [comment]
@ChrisButterworth Yes! But I think everyone is used to `cmd+k`

**Comment by admix** [comment]
@luco ```cmd+k``` is already used by Pane->Previous.. which is not that great imo.. mb combinations like: ```cmd+]``` and ```cmd+[``` would be better, however its a topic to the other issue.

**Comment by dperrymorrow** [comment]
i was confused by cmd+k not working at first as well, then i discovered that clear is a suggested command
![black screen 2017-05-18 15-16-06](https://cloud.githubusercontent.com/assets/64978/26225637/fed4fecc-3bdc-11e7-806d-22bc8755d21f.png)

**Comment by vlad-shatskyi** [comment]
Closing. Please use <kbd>Ctrl</kbd>+<kbd>L</kbd>
