### ISSUE TITLE
Pass vttest

### ISSUE THREAD

**Issue by vlad-shatskyi** [railsware/upterm#61]
http://www.columbia.edu/kermit/vttest.html
###### Cursor movements
- [x] Movements box (80 columns)
- [x] Movements box (132 columns)
- [x] Movements wrap (80 columns)
- [x] Movements wrap (132 columns)
- [x] Movements cursor-controls in ESC sequences
- [x] Movements leading zeros in ESC sequences

**Comment by jerch** [comment]
Passing vttest is a big deal. You would have to implement most of the DEC primitives the right way and the documentation of those is lousy. Best source would be http://vt100.net and source code of popular emulators like xterm or rxvt.
I tried to set up test cases for the primitives based upon xterm output. You can find them here https://github.com/netzkolchose/node-ansiterminal/tree/master/test. The test cases are still work in progress, tough you might find them useful somehow.

**Comment by shockone** [comment]
Thank you @jerch. If only there was a test suite failing with a message like `CUB should not wrap at the edge of the screen`. Instead, you can see that the output looks different, but have no idea why.

**Comment by jerch** [comment]
Yeah esp. the last column handling is awkward. I started to support unicode with fullwidth characters in node-ansiterminal - it is a total mess at the last column. No clue yet how to solve this in a clean way but it needs refactoring -.-

**Comment by shockone** [comment]
We could create an independent suite which would work for any terminal implementation (maybe the requirement would be to render to a 2d array of characters for the suite, but I'm not sure).

**Comment by jerch** [comment]
Hmm, separate the frontend stuff (user events and output) from the low level vt stuff - thats the reason why I splitted the whole stuff in node-ansiterminal and the jquery.browserterminal as the frontend (while the latter is still quick&dirty "can I get this run"-code).
Not sure if a separation like this will do for your needs since you have much more functionality in mind (my goal is to get a full featured classical vt emulation in the browser, which comes with some restrictions like no node types etc). But if you are cool with that we could try to build something like "libvt" for node/browser as a basic vt drop-in stack (tested of course :D).

**Comment by shockone** [comment]
I was thinking of something like https://github.com/karlcow/markdown-testsuite, which provides an independent set of tests for every MarkDown implementation in the world. 

I would like the suite to be able to test xterm, iTerm 2, and others. It would give us an immediate benefit of having a reference implementation (if it works in xterm, it should work in whatever-terminal) and a delayed benefit of simplifying the lives of other people who want to create a new terminal.

**Comment by jerch** [comment]
Ah got you. Well it should be possible but would require a well crafted testsuite with adapters to other languages (as test drop-ins into xterm source etc). Biggest problem would be to get all the right definitions of all (or at first most common) modi a terminal can switch to (xterm has tons of different emulation modi).

**Comment by shockone** [comment]
Hooray, the first screen looks perfect!
![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/9il21yih.png)

**Comment by kbrock** [comment]
vttest looks like a worthy (and ambitious goal).

The [node-ansiterminal test] looks like a great start. Very easy to catch regressions. Seems it may be difficult hook into the right portion of the terminal emulator though.

Looks like the xterm faq is moslty focused on the [number of supported functions] and [visual differences] of the various implementation. If you wanted to create a test suite to be used across multiple terminal emulators, probably would be best to stick to that. Maybe standardize on screen size, font, font size, and compare screen shots?

[number of supported functions]: http://invisible-island.net/xterm/xterm.faq.html#compare_versions
[visual differences]: http://invisible-island.net/vttest/
[node-ansiterminal test]: https://github.com/netzkolchose/node-ansiterminal/tree/master/test

Very cool project. Thanks all
