### ISSUE TITLE
Ctrl+w does not reliably delete words left from the cursor

### ISSUE THREAD

**Issue by haimich** [railsware/upterm#737]
I noticed that deleting words with Ctrl+w does always delete the word on the right side regardless of where the cursor is. Example:

`$ echo "this is just a test"`

When you position the cursor between "just" and "a" and use ctrl+w it will first delete "test". The expected behaviour would be that "just" gets deleted.

**Comment by vshatskyi** [comment]
Related issue: https://github.com/vshatskyi/black-screen/issues/1015

**Comment by vlad-shatskyi** [comment]
@haimich this feature was removed. Please use `Ctrl+Backspace` instead.
