### ISSUE TITLE
YAML Prettifier

### ISSUE THREAD

**Issue by zedtux** [railsware/upterm#74]
Like it's done for JSON, Black-Screen should handle YAML files :)

**Comment by G07cha** [comment]
Thanks for contribution, I've done some research and found [JavaScript lib](https://github.com/nodeca/js-yaml) that can parse YAML files. Notify us if you want work on this issue.

**Comment by N00D13** [comment]
I want work on this issue!

**Comment by G07cha** [comment]
We will be grateful to you, @N00D13, make sure that you read [contributing guide](https://github.com/black-screen/black-screen/blob/master/CONTRIBUTING.md).

**Comment by zedtux** [comment]
Thank you @N00D13 ! :+1:

**Comment by shockone** [comment]
Hey, @N00D13. It's great you decided to help! You might find this comment useful. https://github.com/black-screen/black-screen/issues/48#issuecomment-138555618

**Comment by zedtux** [comment]
@N00D13 do you still plan to work on it or shall I close the issue?
