### ISSUE TITLE
Feature Request: Fuzzy matching 

### ISSUE THREAD

**Issue by Alok** [railsware/upterm#820]
I typed the following text:

`vim a`

and immediately got a list of files/dirs that started with 'a'. Which is very nice. Could that matching be made fuzzy?

e.g.  i have a file named `abcdefg` and if I type `vim ag`, it would still show up as an option.

**Comment by drew-gross** [comment]
Sublime has a very good implementation of this. This isn't a priority for me, but if someone else would like to take it on, I have one request for you, which is that fuzzy matches are the lowest priority in the UI (eg. prefix matches should always appear before over fuzzy matches)
