### ISSUE TITLE
Better Autocomplete Search

### ISSUE THREAD

**Issue by pmkary** [railsware/upterm#873]
Autocomplete in BS only matches the start of the identifiers which is a bit bad. Good autocomplete search finds the given string as a sequence of characters and then finds it as a sequence in identifiers, such as:

<img width="548" alt="screen shot 2016-11-06 at 11 17 05 pm" src="https://cloud.githubusercontent.com/assets/2157285/20041017/89df015a-a477-11e6-9d6e-de25d599a4c0.png">

I once tried to make an suggestion provider for my language and then I tried to make [an editor for it, which is available here for testing](http://www.karyfoundation.org/research/playgrounds/gerda/02/). And it gives you something like this:

<img width="256" alt="screen shot 2016-11-06 at 11 07 53 pm" src="https://cloud.githubusercontent.com/assets/2157285/20040931/0658f0bc-a476-11e6-9283-dabf855138ae.png">

I said that because I have an implementation for this algorithm in TypeScript, so you can use it with some changes. It also inserts spans in the text to make it color (what chars are in the sequence):

```TypeScript
export function FilterSuggestions( suggestions: Array<string> , userInput: string ) {
    var results = new Array<string>( );
    for ( var index = 0; index < suggestions.length; index++ ) {
        var element = suggestions[ index ];
        var currentSearchCharIndex = 0;
        var elementToBeAdded = '';
        for ( var searchStringsIndex = 0; searchStringsIndex < element.length; searchStringsIndex++) {
            var currentChar = element[ searchStringsIndex ];
            if ( currentChar == userInput[ currentSearchCharIndex ] ) {
                if ( currentSearchCharIndex < userInput.length ) {
                    elementToBeAdded += '<span class="GerdaItemHighlighters">' + currentChar + '</span>';
                    currentSearchCharIndex++;
                } else {
                    elementToBeAdded += currentChar;
                }
            } else {
                elementToBeAdded += currentChar;
            }
        }
        if ( currentSearchCharIndex >= userInput.length ) {
            results.push( elementToBeAdded );
        }
    }
    return results;
}
```

I tried to implement it to the BS but the code base is a bit strange and I don't get where to start. So if you give me some points on where to implement these stuff I can do this myself.

**Comment by drew-gross** [comment]
Cool. Black Screen uses React so you will have to modify your algorithm somewhat, as appending spans as text isn't really how React works.

The React component that renders suggestions is `SuggestionComponent` here: https://github.com/shockone/black-screen/blob/master/src/views/AutocompleteComponent.tsx#L12

You will probably also have to modify the `Suggestion` class in `plugins/autocompletion_utils/Common.ts` and the `getSuggestions` function in `src/Autocompletion.ts`

I also suggest that infix/sequence matches have the lowest priority after prefix matches and autocomplete from plugins.

**Comment by pmkary** [comment]
Awesome, I'm on it. it's very likely that I comeback with more questions but I think this is what I needed for now. Thanks a lot!

**Comment by drew-gross** [comment]
No problem!

**Comment by pmkary** [comment]
So the good news is that the filter worked very awesome by just replacing the old `.startsWith` function:

![first-true-filter](https://cloud.githubusercontent.com/assets/2157285/20080223/bb7725ee-a55d-11e6-8819-ba47797e81c9.gif)

I have to make the suggestions color, that's the next thing. But I now have a question. My last pull request has not be merged. And I have used github so much but I've always been the repo owner. Or I had only one pull request. If I now push to my master it will be appended to the design PR. What should I do about that? Branching works but then making pull requests get a bit strange...

**Comment by drew-gross** [comment]
Making pull requests is actually really easy from a branch, GitHub lets you create a pull request from `branch_name` in your repo to `master` in our repo. You just need to make sure your branch diverges from `master` before the changes you added in the other PR.

**Comment by pmkary** [comment]
## Progress @ 60%

Highlighting the sequence is now complete:

<img width="572" alt="screen shot 2016-11-08 at 1 52 42 pm" src="https://cloud.githubusercontent.com/assets/2157285/20095462/d679fe22-a5ba-11e6-8ae9-bb932d397a7a.png">

But something remains in here. With very large suggestions comes this:

<img width="1279" alt="screen shot 2016-11-08 at 1 50 35 pm" src="https://cloud.githubusercontent.com/assets/2157285/20095510/fcf32a2e-a5ba-11e6-89b2-f11036e22894.png">

I will simple ignore the length over 50 chars for now. I think it's good. But I need some better solutions for this. Would be good if you give me some ideas...

**Comment by shockone** [comment]
History suggestions don't belong here anyway; we should move them to reverse history search when it's implemented.

**Comment by shockone** [comment]
We can either truncate long suggestions (as `fzf` does), or just make sure the following lines are indented not to be under the icon (most likely using CSS Grid). It's OK if you don't do any of that, @pmkary.

**Comment by pmkary** [comment]
As I said I've implemented a simple truncation logic to filter anything above 40 chars. But the full plan you're suggesting is much better. For now I will implement a system for sorting suggestions on their priority. Then I think I'll make a PR so then you can check it out...

**Comment by drew-gross** [comment]
Another alternative would be to just put white-space nowrap and overflow ellipses on the suggestion element.

**Comment by pmkary** [comment]
@drew-gross I tried to make that work but then I though I have no idea what the max-width of the suggestions bar must be. And there comes another problem and it's that imagine 50 chars in the start of two both suggestions be the same. How can you differ one from another? I think we should test every one of these ideas to see which one is actually more handy.

**Comment by pmkary** [comment]
## Progress 100%
I think there is no need for any sort algorithm. The base sort is still the best. I tried far to many of them and the one that already is there is the best.

**Comment by drew-gross** [comment]
I think white-space nowrap and overflow ellipses works for any size div.

For detecting the difference between long commands, I think that as long as the full command is show in the input bar when you select it, thats fine.

**Comment by pmkary** [comment]
@drew-gross that actually is pretty great idea. Let me work on that... (The next PR!)
