### ISSUE TITLE
Autocomplete overflow handling

### ISSUE THREAD

**Issue by pmkary** [railsware/upterm#878]
So after the talks we had on #873 this is my implementation. I now show at "most" 50 chars and append a green `...` text at the end. Which makes it a stylish and yet functional autocomplete:

<img width="559" src="https://cloud.githubusercontent.com/assets/2157285/20149425/66b0449a-a6c6-11e6-9d75-d5359a86555b.png">

However the problem is still how to make it work for user to find out which is which. If type the start of the sequence @drew-gross's idea gets happened:

<img width="823" alt="screen shot 2016-11-09 at 9 59 02 pm" src="https://cloud.githubusercontent.com/assets/2157285/20149734/d969c276-a6c7-11e6-804b-c32d24442997.png">

But when you use the sequence in between you no longer get that:

<img width="784" alt="screen shot 2016-11-09 at 9 59 13 pm" src="https://cloud.githubusercontent.com/assets/2157285/20149781/fe984694-a6c7-11e6-8378-645610cfa9d5.png">

So I'm here to implement whatever the idea is :D
Let's talk more...

**Comment by drew-gross** [comment]
This can be done with the `text-overflow: ellipsis` CSS property https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by pmkary** [comment]
@drew-gross yeah but can you color them?

**Comment by drew-gross** [comment]
Yep: http://jsfiddle.net/rz4kLg3c/1/

**Comment by shockone** [comment]
I wouldn't color them. Coloring is a mean of getting attention, and the dots don't require my attention.

**Comment by pmkary** [comment]
Well exactly for that I added colors to indicated that the suggestion is overflowed...
