### ISSUE TITLE
`⌘+R` destory all tabs/sessions

### ISSUE THREAD

**Issue by em-yuanbo** [railsware/upterm#997]
and where are the running processes in sessions going?

**Comment by drew-gross** [comment]
I actually don't know. If anyone finds out, please post here!

**Comment by vshatskyi** [comment]
All the running processes receive `SIGINT`. What should happen on cmd+r, @em-yuanbo?

**Comment by vlad-shatskyi** [comment]
Now it's cmd+shift+r.
